/*
 * settings_const.hpp
 *
 *  Created on: 15 апр. 2026 г.
 *      Author: Kirill
 */

#ifndef MAIN_COMMON_CONST_SETTINGS_CONST_HPP_
#define MAIN_COMMON_CONST_SETTINGS_CONST_HPP_

#define TEMP_SENSOR_TYPE "TEMP_SENSOR_TYPE"
#define DUST_SENSOR_TYPE "DUST_SENSOR_TYPE"

#define INVENTOR_NUM 	   "INVENTOR_NUM"
#define FREQ_TEMP_SENSOR_1 "FREQ_TEMP_SENSOR_1"
#define FREQ_TEMP_SENSOR_2 "FREQ_TEMP_SENSOR_2"
#define FREQ_TEMP_SENSOR_3 "FREQ_TEMP_SENSOR_3"
#define FREQ_TEMP_SENSOR_C "FREQ_TEMP_SENSOR_C"
#define FREQ_DUST_SENSOR_1 "FREQ_DUST_SENSOR_1"
#define FREQ_DUST_SENSOR_2 "FREQ_DUST_SENSOR_2"

#define WIFI_NAME "WIFI_NAME"
#define WIFI_PASS "WIFI_PASS"

#define DATE "DATE"
#define TIME "TIME"
#define DATE_TIME "DATE_TIME"

#endif /* MAIN_COMMON_CONST_SETTINGS_CONST_HPP_ */
